name: ""
title: Jan Thomas Müller

author:
  name: "Jan T. Müller"
  email: "mail@jantmueller.com"

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: dark
  header_pages:
    - resume.md
  social_links:
    - { icon: github, url: "https://github.com/janthmueller"}
    - { icon: linkedin, url: "https://www.linkedin.com/in/jantmueller/"}
